theme: jekyll-theme-minimal
title: Data cuisiniers : How to measure actors success ? 
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
