theme: jekyll-theme-minimal
title: Data cuisiniers : How to quantify the actors success ? 
description: Website for project ADA 
show_downloads: True
navigation:
  - title: Home
    url: /ada-2023-project-datacuisiniers
  - title: Example
    url: example
